version 2.0

diff --git a/lib/bmtLinux b/lib/bmtLinux
--- a/lib/bmtLinux
+++ b/lib/bmtLinux
@@ -1,23 +1,24 @@
 #!/bin/bash
 
-#=========================HEADER==========================================
+# === HEADER ===
 #FileName: bmtLinux
 #Function: Contains linux related utilities
 #library name: bashmultitool
-#Written: Gavin Lyons
 #URL: https://github.com/gavinlyonsrepo/BashMultiTool
 
-#====================FUNCTIONS===============================
+# === FUNCTIONS ===
 
 function bmtLinuxFunc
 {
-local   red=$(printf "\033[0;31m")
-local   normal=$(printf "\033[0m")
+local   red
+red=$(printf "\033[0;31m")
+local   normal
+normal=$(printf "\033[0m")
 local   pacVar=""
 
 case "$1" in
 
-	checkpac) #7 check if package installed
+	checkpac) # 401 check if package installed
 		case "$3" in
 			1)  # pacman based
 				pacVar=$(pacman -Qqs "$2")
@@ -47,7 +48,7 @@ case "$1" in
 			return 0
 		else #not installed
 			#if text input is MES print install bad message
-			if [ "$4" = "MES" ]
+			if [ "$4" = "MES" ];
 			then
 				printf '%s\n' "${red}$2 is Not installed ${normal}"
 			fi
@@ -55,7 +56,7 @@ case "$1" in
 		fi
 	;;
 
-	distrocheck) #9 check what distro on
+	distrocheck) #402 check what distro on
 			if [ -f /etc/redhat-release ]; then
 				# rpm based
 				return 2
@@ -75,12 +76,12 @@ case "$1" in
 				# slackware based
 				return 7
 			else
-				printf '%s\n' "Unsupported Linux distro"
+				printf '%s\n' "UnKnown Linux distro"
 				return 52
 			fi
 	;;
 
-	isTextEdSet) #12 set text editor
+	isTextEdSet) #403 set text editor
 		if [ -z "${EDITOR}" ]
 		then
 			export EDITOR="vi"
@@ -90,34 +91,79 @@ case "$1" in
 		fi
 	;;
 
-	log)
+	log) #404
 		declare logdatfVar="%FT%T%z"
 		local logstrVar=""
-		local logmsgVar="$3"
 		local statusVar="$2"
-		declare logfileVar="$4.log"
-		local dateVar=$(date +"$logdatfVar")
+		local logmsgVar="$3"
+		logfileVar="$4.log"
+		local dateVar
+		dateVar=$(date +"$logdatfVar")
 		
-		#error $statusvar
+		# Check that $statusvar is valid
 		case "$statusVar" in
 		EMERGENCY|ALERT|CRITICAL|ERROR|WARNING|NOTICE|INFO|DEBUG|OK|FAILED|PASSED) : ;;
 		*) printf '%s\n' "Error bmtLinux : log : Invalid state : $statusVar"
 				return 55 ;;
 		esac
+		
+		# Create the log message
 		if [ -n "$logmsgVar" ]
 		then
 			logstrVar="$dateVar - $statusVar - $logmsgVar"
 		else
 			logstrVar="$dateVar -- empty log message"
 		fi
-
+		
+		mkdir -p "$5"
 		echo "$logstrVar" >> "$5$logfileVar"
+		
+		# If param 6 added echo as well as log
+		[ "$6" = "MES" ] && echo "$logstrVar" 
 		return 0
 	;;
-
+	
+	user) #405 	
+	[ -z "$2" ] && return 1
+	if id -u "$2" >/dev/null 2>&1; then
+		return 0
+	else
+		return 2
+	fi
+	;;
+	
+	isvarempty) #406
+		local var_name="$2"
+		local var_value="${!var_name}"
+		if [[ -v "$var_name" ]]; then
+		   if [[ -n "$var_value" ]]; then
+			 return 0 # "set and non-empty"
+		   else
+			 return 2 # "set and empty"
+		   fi
+		else
+			return 3 # "unset"
+		fi
+	;;
+	
+	runasroot) #407
+	if [[ ${EUID} -ne 0 ]]; then
+		printf '%s\n' "${red} Error :: This script must run as root, program exiting! ${normal}"
+		return 2
+	else
+		echo "Info :: Running as root"
+		return 0
+	fi
+	;;
+	
+	iscommand) #408 
+		hash "$2" 2>/dev/null || return 2
+		return 0
+	;;
+	
 	*) # Catch all user typos
 		printf '%s\n'  "Error: Unknown keyword : bashmultitool :bmtLinux: bmtLinuxFunc"
-		return 50
+		return 255
 	;;
 esac
 }
diff --git a/lib/bmtMisc b/lib/bmtMisc
--- a/lib/bmtMisc
+++ b/lib/bmtMisc
@@ -1,91 +1,111 @@
 #!/bin/bash
-
-#=========================HEADER==========================================
+# === HEADER ===
 #FileName: bmtMisc
 #Function: Contains miscellaneous utilities.
 #library name: bashmultitool
 #Written: Gavin Lyons
 #URL: https://github.com/gavinlyonsrepo/BashMultiTool
 
-#====================FUNCTIONS===============================
+# ===FUNCTIONS ===
 
 function bmtMiscFunc
 {
-local   red=$(printf "\033[0;31m")
-local	normal=$(printf "\033[0m")
+
 case "$1" in
 
-	spin) # 1 animation
-		local spinner=( Ooooo oOooo ooOoo oooOo ooooO oooOo ooOoo oOooo);
-		while true; do
-			for i in "${spinner[@]}";
-			do
-				# no new line , \r reset line
-				echo -ne "\r$i";
-				sleep 0.2;
-			done;
-		done
-	;;
-
-
-	checknet) # 2 check if website up
-			#This uses netcat (nc) in its port scan mode,
-			#a quick poke (-z is zero-I/O mode [used for
-			#scanning]) with a quick timeout
-			#(-w 1 waits at most one second
-			#It checks passed website $1 on port 80 (HTTP).
-		if nc -zw1 "$2" 80; then
-			printf '%s\n' "We have connectivity $2"
+	password) #801
+		local mylengthVar=0
+		if [ -z "$2" ]; then
+			cd "/tmp/"  || return 3
+		else
+			cd "$2"  || return 3
+		fi
+		touch passwordBMT.txt
+		echo "Random Password generator"
+		echo "Enter length:-"
+		read -r mylengthVar
+		# if just enter pressed set default 20
+		if [ -z "$mylengthVar" ]; then
+			mylengthVar=20
+		fi
+		#check integer
+		if [[ "$mylengthVar" != *[!0-9]* ]];then
+			echo -n "$(< /dev/urandom tr -dc "_*?#!A-Z-a-z-0-9" | head -c "$mylengthVar";)">passwordBMT.txt
+			echo "Password generated"
 			return 0
 		else
-			printf '%s\n' "${red}We do not have connectivity $2 ${normal}"
 			return 2
 		fi
 	;;
-	# 3  Displays the current timestamp
-	now) date +%s%N ;;
+	
+	getbatlevel) #802
+		local Filepath="/sys/class/power_supply/$2/capacity"
+		if ! [[ -f $Filepath ]]; then
+			echo "File '$Filepath' not found."
+			return 101
+		elif ! [[ -f $Filepath ]]; then
+			echo "File '$Filepath' unreadable."
+			return 102
+		fi
 
-	# 4 Displays the time elapsed between two times
-	elapsed)
-		local startVar="$2"
-		local stopVar="$3"
-		local diffVar="" 
-		#https://serverfault.com/questions/151109/how-do-i-get-current-unix-time-in-milliseconds-using-bash#151112
-		diffVar=$(echo "scale=6;($stopVar - ${startVar})/(1*10^09)" | bc)
-		echo "$diffVar"
-	;;
-	
-	# 5 Starts the timer
-	startWatch)
-		__BMT_START_WATCH=$(bmtMiscFunc now) 
-	;;
-	
-	# 6 Stops the timer
-	stopWatch)
-		if [ -n "$__BMT_START_WATCH" ] 
+		read -r < "/sys/class/power_supply/$2/capacity"
+		if [ "$3" = "MES" ]
 		then
-			local stopWatchVar=0
-			stopWatchVar=$(bmtMiscFunc now)
-			bmtMiscFunc elapsed "$__BMT_START_WATCH" "$stopWatchVar" 
-			return 0
-		else
-			return 2
+			printf 'Battery is at %d%% capacity.\n' "$REPLY" # Reply is built into read.
 		fi
+		return "$REPLY"
 	;;
 	
-	# 7
-	weather)
-		echo "3 day weather forecast by WTTR.IN"
-		echo "Type a City name, airport code, domain name or area code:-"
-		local mycityVar=""
-		read -r mycityVar		
-		clear
-		curl wttr.in/"$mycityVar"
+	drawbox) #803
+		local width
+		local place
+		local textarray=("$@") 
+		local colorbox="$2"
+		local colortext="$3"
+		local inputparam
+		
+		# remove color's and subsection name from array
+		for inputparam in 0 1 2 
+		do
+			unset 'textarray[inputparam]'
+		done
+			
+		#${s[@]} – all elements of array s; ((width<${#l})) – ((..)) shell arithmetic testing 
+		#whether variable width's value is less than variable l value's length, obtained
+		#with parameter expansion (# – string length); ${place//?/-} – parameter expansion  
+		#replacing all occurrences of any character with a “-” (// – replace all; ? – 
+		#wildcard meaning any character). 
+		for word in "${textarray[@]}"; do
+			((width<${#word})) && { place="$word"; width="${#word}"; }
+		done
+		tput setaf "$colorbox"
+		echo -e " -${place//?/-}-\n| ${place//?/ } |"
+		for word in "${textarray[@]}"; do
+			printf '| %s%*s%s |\n' "$(tput setaf "$colortext")" "-$width" "$word" "$(tput setaf "$colorbox")"
+		done
+		echo -e "| ${place//?/ } |\n -${place//?/-}-"
+		tput sgr 0
+	;;
+	
+	title)
+		local colorbox="$2"
+		local colortext="$3"
+		local bannersymbol="$4"
+		local textmsg="$5"
+		
+		edge=$(echo "$textmsg####" | sed "s/./$bannersymbol/g")
+		
+		tput setaf "$colorbox"
+		printf '%s\n' "$edge"
+		printf '%s%s%s%s%s\n' "$bannersymbol " "$(tput setaf "$colortext")" "$textmsg" "$(tput setaf "$colorbox")" " $bannersymbol"
+		printf '%s\n' "$edge"
+		tput sgr 0
+		
 	;;
 	
 	*) # Catch all users typos
 		printf '%s\n'  "Error: Unknown keyword : bashMultiTool: bmtMisc: bmtMiscFunc"
-		return 50
+		return 255
 	;;
 esac
 }
